# Gunakan image PHP-FPM resmi
FROM php:7.4-fpm

# Install Nginx
RUN apt-get update && apt-get install -y nginx

# Salin file konfigurasi Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Salin semua file dari direktori kerja lokal ke direktori root Nginx
COPY . /var/www/html/

# Set work directory
WORKDIR /var/www/html/

# Expose port 80 untuk akses web
EXPOSE 80

# Jalankan Nginx dan PHP-FPM
CMD ["sh", "-c", "php-fpm -D && nginx -g 'daemon off;'"]
