# Gunakan image PHP resmi dengan Apache
FROM php:7.4-apache

# Salin semua file dari direktori kerja lokal ke direktori root Apache
COPY . /var/www/html/

# Aktifkan modul rewrite Apache
RUN a2enmod rewrite

# Expose port 80 untuk akses web
EXPOSE 80

# Jalankan Apache di foreground
CMD ["apache2-foreground"]
